/* client-server */
export const GET_PROFILE = 'GET_PROFILE';

export const GET_CHALLENGES = 'GET_CHALLENGES';
export const GET_MORE_CHALLENGES = 'GET_MORE_CHALLENGES';
export const GET_CHALLENGE_BY_ID = 'GET_CHALLENGE_BY_ID';
export const GET_CHALLENGES_BY_USER_ID = 'GET_CHALLENGES_BY_USER_ID';
export const GET_MORE_CHALLENGES_BY_USER_ID = 'GET_MORE_CHALLENGES_BY_USER_ID';
export const GET_GAME_CHALLENGES = 'GET_GAME_CHALLENGES';
export const SET_CHALLENGE_STATE = 'SET_CHALLENGE_STATE';
export const SET_CHALLENGES_FILTER = 'SET_CHALLENGES_FILTER';
export const SET_CHALLENGES_BY_USER_ID_FILTER = 'SET_CHALLENGES_BY_USER_ID_FILTER';
export const SET_CHALLENGES_BY_USER_ID_SEARCH_TERM = 'SET_CHALLENGES_BY_USER_ID_SEARCH_TERM';
export const SET_CHALLENGES_SEARCH_TERM = 'SET_CHALLENGES_SEARCH_TERM';
export const POST_CHALLENGE = 'POST_CHALLENGE';
export const UPDATE_CHALLENGE = 'UPDATE_CHALLENGE';
export const UPDATE_WIDGET_CHALLENGE = 'UPDATE_WIDGET_CHALLENGE';

export const GET_STREAMERS = 'GET_STREAMERS';
export const GET_MORE_STREAMERS = 'GET_MORE_STREAMERS';
export const SET_ACTIVE_STREAMER = 'SET_ACTIVE_STREAMER';
export const SET_ACTIVE_STREAMER_CLIENTSIDE = 'SET_ACTIVE_STREAMER_CLIENTSIDE';
export const RESET_ACTIVE_STREAMER = 'RESET_ACTIVE_STREAMER';
export const SET_STREAMERS_SEARCH_TERM = 'SET_STREAMERS_SEARCH_TERM';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_ACTIVE_TRANSACTION = 'ADD_ACTIVE_TRANSACTION';
export const SET_ACTIVE_TRANSACTION = 'SET_ACTIVE_TRANSACTION';
export const REMOVE_ACTIVE_TRANSACTION = 'REMOVE_ACTIVE_TRANSACTION';

export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_MIN_PAYMENT = 'GET_MIN_PAYMENT';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

export const GET_TEMPLATES = 'GET_TEMPLATES';
export const SET_TEMPLATES_FILTER = 'SET_TEMPLATES_FILTER';

export const SET_CREATE_CHALLENGE_DESCRIPTION = 'SET_CREATE_CHALLENGE_DESCRIPTION';
export const SET_CREATE_CHALLENGE_TYPE = 'SET_CREATE_CHALLENGE_TYPE';
export const SET_CREATE_CHALLENGE_TITLE = 'SET_CREATE_CHALLENGE_TITLE';
export const SET_CREATE_CHALLENGE_DRAFT = 'SET_CREATE_CHALLENGE_DRAFT';

export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';



/* CLIENT */
export const SET_FORM_VISIBILITY = 'SET_FORM_VISIBILITY';

export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const OPEN_UNREGISTRED = 'OPEN_UNREGISTRED';
export const CLOSE_UNREGISTRED = 'CLOSE_UNREGISTRED';

export const SET_WIDGET_CHALLENGE = 'SET_WIDGET_CHALLENGE ';
export const RESET_WIDGET_CHALLENGE = 'RESET_WIDGET_CHALLENGE ';
export const SET_REDIRECT_TO_CHALLENGE = 'SET_REDIRECT_TO_CHALLENGE';
export const UNSET_REDIRECT_TO_CHALLENGE = 'UNSET_REDIRECT_TO_CHALLENGE';
export const RESET_FILTERS = 'RESET_FILTERS';

export const SET_ACTIVE_PAYMENT = 'SET_ACTIVE_PAYMENT';
export const RESET_ACTIVE_PAYMENT = 'RESET_ACTIVE_PAYMENT';
