export default {
    OK: 'OK',
    CHALLENGE_AMOUNT_UPDATED: 'CHALLENGE_AMOUNT_UPDATED',
    ALREADY_EXECUTED: 'ALREADY_EXECUTED',
    CHALLENGE_STATE_UPDATED: 'CHALLENGE_STATE_UPDATED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    PS_ERROR: 'PS_ERROR',
    PS_UNAVAILABLE: 'PS_UNAVAILABLE'
}