export default {
    HELP: 'HELP',
    ACCEPT_DISCLAIMER: 'ACCEPT_DISCLAIMER',
    DONATE_DISCLAIMER: 'DONATE_DISCLAIMER',
    ACCEPT_CHALLENGE: 'ACCEPT_CHALLENGE',
    UNREGISTRED: 'UNREGISTRED',
    PAYMENT_METHODS: 'PAYMENT_METHODS',
    PAYMENT_CRYPTO: 'PAYMENT_CRYPTO'
}